package com.test.common_entity

import java.io.Serializable

data class Movie(
    val id: Int,
    val link_type: String? = null,
    val link_key: String? = null,
    val theme: String? = null,
    val output_type: String? = null,
    val movie_id: Int? = 0,
    val uid: String? = null,
    val movie_title: String? = null,
    val movie_title_en: String? = null,
    val tag_id: String? = null,
    val serial: Serial? = null,
    val watermark: Boolean? = null,
    val hD: Boolean? = null,
    val watch_list_action: String? = null,
    val commingsoon_txt: String? = null,
    val badge: Badge? = null,
    val rate_enable: Boolean? = null,
    val rate_enable_by_cnt: Boolean? = null,
    val descr: String? = null,
    val cover: String? = null,
    val publish_date: String? = null,
    val age_range: String? = null,
    val pic: Pic? = null,
    val rate_avrage: String? = null,
    val avg_rate_label: String? = null,
    val pro_year: String? = null,
    val imdb_rate: String? = null,
    val categories: List<Categories>? = null,
    val duration: Duration? = null,
    val countries: List<Countries>? = null,
    val dubbed: Dubbed? = null,
    val subtitle: Subtitle? = null,
    val audio: Audio? = null,
    val language_info: Language_info? = null,
    val director: String? = null,
    val last_watch: List<String>? = null,
    val freemium: Boolean? = null,
    val position: Int? = 0,
    val sid: Int? = 0,
    val uuid: String? = null,
): Serializable
